apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
  namespace: autoscale-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-for-autoscale
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 20 
