apiVersion: v1
kind: Namespace
metadata:
  name: test-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-demo-1
  namespace: test-app
data:
  default.conf.template: |
    server {
        listen 80;
        server_name localhost;

        location /app1 {
            alias /usr/share/nginx/html;
            index index.html index.htm;

            add_header Content-Type text/html;
            sub_filter 'POD_NAME' '${POD_NAME}';
            sub_filter_once on;
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Nginx</title>
    </head>
    <body>
        <h1>Welcome to Nginx!</h1>
        <p>If you see this page, the Nginx web server is successfully configured.</p>
        <p>Learn more about deploying and managing applications with Kubernetes in our comprehensive Kubernetes course.</p>
        <p>THIS IS APP-1! Pod Name: POD_NAME</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-demo-1
  namespace: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alb-demo-1
  template:
    metadata:
      labels:
        app: alb-demo-1
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: config-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: config-volume
          configMap:
            name: alb-demo-1
---
apiVersion: v1
kind: Service
metadata:
  name: alb-demo-1
  namespace: test-app
spec:
  selector:
    app: alb-demo-1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

